services:
  kvd:
    build: .
    command:
      - --capacity=1000
      - --shards=16
      - --mutex-type=sync.Mutex
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512MB
    ports:
      - 6060:6060
      - 8080:8080

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    profiles:
      - observability
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    profiles:
      - observability
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE=true

volumes:
  prometheus:
  grafana:
